force-app/main/default/objects/Account/fields/Community_Group_Host__c.field-meta.xml
<CustomField>
    <fullName>Community_Group_Host__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Household hosting a Community Group</description>
    <inlineHelpText>Household hosting a Community Group</inlineHelpText>
    <label>Community Group Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLC_Community_Group__c/CLC_Community_Group__c.object-meta.xml
<CustomObject>
    <description>Object to store attributes for Community Group data records</description>
    <label>Community Group</label>
    <nameField>
        <label>Community Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLC_Community_Group__c/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <formula>Group_Location__r.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BillingCity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLC_Community_Group__c/fields/BillingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingPostalCode__c</fullName>
    <formula>Group_Location__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BillingPostalCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLC_Community_Group__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <formula>Group_Location__r.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BillingState</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLC_Community_Group__c/fields/BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>BillingStreet__c</fullName>
    <formula>Group_Location__r.BillingStreet</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BillingStreet</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLC_Community_Group__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <formula>Group_Location__r.BillingLatitude</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLC_Community_Group__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <formula>Group_Location__r.BillingLongitude</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NPSP_CommunityGroupController.cls
public with sharing class NPSP_CommunityGroupController {

    @AuraEnabled(Cacheable=true)
    public static List<CLC_Community_Group__c> getAllGroups() {
        return [SELECT Id, Name, BillingStreet__c, BillingCity__c,
                BillingState__c, BillingPostalCode__c, Latitude__c, 
                Longitude__c 
                FROM CLC_Community_Group__c ORDER BY Name LIMIT 100];        
    }
    @AuraEnabled(Cacheable=true)
    public static List<CLC_Community_Group__c> searchGroups(String searchTerm) {
        // Return all bears when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllGroups();
        }
        // Prepare query paramters
        searchTerm = '%'+ searchTerm +'%';
        // Execute search query
        return [SELECT Id, Name, BillingStreet__c, BillingCity__c,
                BillingState__c, BillingPostalCode__c, Latitude__c, 
                Longitude__c
                FROM CLC_Community_Group__c 
                WHERE Name LIKE :searchTerm ORDER BY Name LIMIT 50];
    }    

    /*
    public static List<Account> getAllGroups() {
        return [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingCountry,
                Location__Latitude__s, Location__Longitude__s
            FROM Account WHERE Community_Group_Host__c = TRUE ORDER BY Name LIMIT 50];
    }
    
    @AuraEnabled(Cacheable=true)
    public static List<Account> searchGroups(String searchTerm) {
        // Return all bears when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllGroups();
        }
        // Prepare query paramters
        searchTerm = '%'+ searchTerm +'%';
        // Execute search query
        return [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingCountry,
                Location__Latitude__s, Location__Longitude__s
                FROM Account 
                WHERE Community_Group_Host__c = TRUE 
                AND Name LIKE :searchTerm ORDER BY Name LIMIT 50];
    }  
    **/  
}